auto: true
server: true
exclude:
  - README.md
  - api
  - tmp
  - bin
  - data_store
  - pillbox-original-process
baseurl: 
highlighter: rouge
permalink: /:docs.html
markdown: kramdown
kramdown:
  input: GFM